### ISSUE TITLE
Dead links in Component Whitelists

### ISSUE THREAD

**Issue by kyuff** [versioneye/versioneye#630] opened 2016-08-02 07:28 UTC
I have created a few component whitelists that I want to delete.
Unfortunately I get a 404 when deleting it.

The URL is like this:

Delete:
https://www.versioneye.com/organisations/[org id]/component_whitelists/[component name]/destroy

Make default
https://www.versioneye.com/organisations/[org id]/component_whitelists/[component name]/default

View Component
https://www.versioneye.com/organisations/[org id]/component_whitelists/[component name]

None of them are working and returns the message: "The page you were looking for doesn't exist."

**Comment by kyuff** [comment] 2016-08-02 08:46
After further investigating, I found out the cause of this problem:

If the Component Name contains a dot (.) things will start failing.

**Comment by reiz** [comment] 2016-08-10 15:23
Hi @kyuff. That's correct. The problem is the . in the name. In the mean while there is a JavaScript validator for that to prevent points in names. If you send the name of your organisation I can delete the whitelist for you from the database.

**Comment by reiz** [comment] 2017-06-07 09:45
@kyuff Does this problem still exist for you? Or can I close this ticket?

**Closed** 2020-10-22 05:12 UTC
